// Content for the 14 lecture decks. Concise, slide-ready teaching points.
module.exports = [
// ===================================================================== L1
{
  num: 1, slug: "Intro_Edge_Pipeline",
  title: "Intelligent Vision Systems & the Edge Pipeline",
  tagline: "From photons to a decision — where vision actually runs.",
  outcomes: [
    { tag: "CLO2", text: "Describe the applied-CV pipeline: capture → inference → decision → action." },
    { tag: "CLO5", text: "Explain the compute-tier ladder and pick a tier for a given task." },
    { tag: "CLO8", text: "Boot every device in the stack and run a 'hello vision' on each." },
  ],
  agenda: ["What 'intelligent vision system' means", "Image formation in one slide", "The compute-tier ladder", "Course tools & hardware", "Ethics & privacy at the edge", "Workshop: hardware bring-up"],
  slides: [
    { t: "content", h: "Beyond a trained model", tag: "PIPELINE", chips: ["latency", "power", "offline"],
      b: ["A model is one block; a system is capture → pre-process → inference → post-process → decision → action.",
          "Real constraints decide the design: latency, power, thermals, offline operation, privacy.",
          "'Applied' means it runs reliably on hardware you can hold — not just in a notebook.",
          "This course optimises the whole pipeline, not just accuracy."],
      note: "Set the framing: we care about deployable systems, not leaderboard numbers." },
    { t: "content", h: "Image formation in one slide", tag: "SENSOR", chips: ["lens", "rolling vs global", "fps"],
      b: ["Light → lens → sensor → pixels; resolution and frame rate are design choices.",
          "Rolling shutter smears fast motion; global shutter freezes it — key for drones.",
          "Colour is fragile: lighting breaks naive RGB thresholds (we fix this in L2).",
          "Every pixel you process costs time and power on the edge."],
      note: "Motivate the Global Shutter camera and the FPS/accuracy trade-off early." },
    { t: "tier", h: "The compute-tier ladder", note: "This ladder recurs all course; ask where each task should run." },
    { t: "content", h: "Course tools & hardware", tag: "TOOLKIT", chips: ["OpenCV", "YOLO", "Hailo"],
      b: ["Classical CV: OpenCV. Real-time capture: picamera2. Training: PyTorch / Ultralytics.",
          "Edge acceleration: Hailo toolchain (HailoRT + Dataflow Compiler).",
          "Microcontroller ML: Edge Impulse on the ESP32-CAM.",
          "Integration: Tello / AI drone, optional ROS 2 bridge."],
      note: "Quick tour; details come in the relevant lectures." },
    { t: "content", h: "Responsible vision at the edge", tag: "ETHICS", chips: ["on-device", "consent", "bias"],
      b: ["On-device inference keeps data local — a genuine privacy advantage.",
          "But cameras in public raise consent, surveillance and bias questions.",
          "Design choice: process and discard, or store? Log the minimum.",
          "Engineers own these trade-offs, not just accuracy metrics."],
      note: "Keep this concrete and tied to their capstone briefs." },
    { t: "figure", img: "figures/fig_pipeline.png", h: "The applied-CV pipeline", cap: "Every stage carries edge constraints — latency, power, offline, privacy.", note: "Use this figure to anchor the systems view." },
  ],
  workshop: { h: "Hardware bring-up & 'hello vision'", code: "SETUP.md · 04_picamera2_stream.py · 08_esp32cam_stream_ingest.py",
    steps: ["Complete SETUP.md for the Pi/Hailo tier and the ESP32 tier.",
            "Run the 5-step smoke test in SETUP §5.",
            "Capture one frame on each tier: Pi camera, Hailo identify, ESP32 web stream.",
            "Record which tier was hardest to bring up and why."],
    deliver: "Notebook page: photo of the assembled Pi 5 + Hailo + camera, the hailortcli identify output, and the ESP32 stream URL.",
    note: "First lab is setup; get all five smoke-test checks green." },
  takeaways: ["A system is the whole pipeline, not just the model.", "Latency, power and offline operation drive edge design.", "The tier ladder (MCU → CPU → NPU → drone) frames every later choice.", "On-device vision is a privacy tool and a responsibility."],
  media: [
    { label: "Raspberry Pi AI HAT+ 2 — setup, object detection & VLM demo", url: "youtube.com/watch?v=kjkJm15RTE8" }
  ],
  resources: [
    { n: "Raspberry Pi AI documentation (Hailo)", u: "raspberrypi.com/documentation/computers/ai.html" },
    { n: "Raspberry Pi AI HAT+ hardware", u: "raspberrypi.com/documentation/accessories/ai-hat-plus.html" },
    { n: "Szeliski — Computer Vision: Algorithms & Applications", u: "szeliski.org/Book" },
  ],
},
// ===================================================================== L2
{
  num: 2, slug: "Image_Fundamentals_OpenCV",
  title: "Image Fundamentals & Classical Processing",
  tagline: "Pixels, colour, filters, edges — the classical toolkit.",
  outcomes: [
    { tag: "CLO1", text: "Represent images as arrays and convert between colour spaces." },
    { tag: "CLO1", text: "Apply filtering, edge detection, thresholding and morphology." },
    { tag: "CLO1", text: "Segment an object robustly under changing lighting." },
  ],
  agenda: ["Images as NumPy arrays", "Colour spaces: BGR / RGB / HSV", "Filtering & noise", "Edges: Sobel, Canny, Laplacian", "Histograms, CLAHE & morphology", "Workshop: colour detector"],
  slides: [
    { t: "content", h: "Images are just arrays", tag: "H × W × C", chips: ["uint8", "BGR!", "ROI"],
      b: ["An image is an H×W×C array of uint8 values (0–255).",
          "OpenCV loads BGR, not RGB — the #1 beginner bug.",
          "Slicing gives you ROIs; drawing primitives annotate frames.",
          "Watch integer overflow: use cv2.convertScaleAbs for safe arithmetic."],
      note: "Demo a BGR/RGB mix-up live so it sticks." },
    { t: "two", h: "Colour spaces — pick the right one", lh: "RGB / BGR", rh: "HSV",
      l: ["Display and storage default.", "Channels entangle colour with brightness.", "Naive thresholds break under lighting change."],
      r: ["Separates Hue from Saturation/Value.", "Threshold on Hue for stable colour detection.", "The go-to for 'find the red object'."],
      note: "HSV is the practical fix for colour segmentation." },
    { t: "process", h: "The classical clean-up pipeline", steps: ["Grayscale", "Blur (Gaussian / median)", "Threshold (Otsu / adaptive)", "Morphology (open / close)", "Canny edges"],
      cap: "Tune each stage — a clean mask makes everything downstream easier.",
      note: "This exact pipeline is the workshop." },
    { t: "content", h: "Edges & contrast", tag: "EDGES", chips: ["Sobel", "Canny", "CLAHE"],
      b: ["Sobel/Laplacian give gradients; Canny adds NMS + hysteresis for clean lines.",
          "Otsu picks a global threshold; adaptive handles uneven lighting.",
          "Histogram equalisation and CLAHE rescue low-contrast images.",
          "Morphology (erode/dilate/open/close) denoises masks before contouring."],
      note: "CLAHE is a strong, underused tool for bad lighting." },
  ],
  workshop: { h: "Interactive pipeline + colour detector", code: "01_opencv_basics.py · 02_filters_edges.py",
    steps: ["Build a trackbar pipeline: blur → threshold → morphology → Canny.",
            "Add an HSV colour detector for a chosen tag/object.",
            "Test under two lighting conditions; note what breaks.",
            "Fix the failure and record the change."],
    deliver: "Before/after montage under two lighting conditions + a paragraph on the failure and your fix.",
    note: "The lighting-failure reflection is the graded insight." },
  takeaways: ["OpenCV is BGR; convert deliberately.", "HSV makes colour detection robust.", "Canny = smoothing + gradient + NMS + hysteresis.", "Morphology cleans masks before you measure anything."],
  media: [
    { label: "OpenCV University — free hands-on CV courses (video)", url: "opencv.org/university/free-courses" }
  ],
  resources: [
    { n: "OpenCV-Python official tutorials", u: "docs.opencv.org/4.x/d6/d00/tutorial_py_root.html" },
    { n: "OpenCV University — free OpenCV course", u: "opencv.org/university/free-opencv-course" },
    { n: "Szeliski — image processing chapters", u: "szeliski.org/Book" },
  ],
},
// ===================================================================== L3
{
  num: 3, slug: "Features_Geometry_MultiView",
  title: "Features, Geometry & Multi-View",
  tagline: "Contours, keypoints, homography and calibration.",
  outcomes: [
    { tag: "CLO1", text: "Detect contours/shapes and ORB keypoint features and match them." },
    { tag: "CLO1", text: "Apply perspective warp / homography (scanner, bird's-eye view)." },
    { tag: "CLO2", text: "Calibrate a camera and correct lens distortion." },
  ],
  agenda: ["Contours & shape measurement", "Keypoints: Harris & ORB", "Matching & homography", "Warp, panorama, HDR", "Camera calibration", "Workshop: calibrate + scan + stitch"],
  slides: [
    { t: "content", h: "Contours & classical features", tag: "FEATURES", chips: ["contours", "ORB", "match"],
      b: ["Contours give area, perimeter, bounding boxes and simple measurement.",
          "Harris finds corners; ORB gives keypoints + descriptors, free and fast.",
          "Match with a BFMatcher (Hamming for ORB) to align two views.",
          "Classical features still win when power is tiny and no training is possible."],
      note: "Position classical features as the low-power, no-training baseline." },
    { t: "content", h: "Geometry: homography in action", tag: "WARP", chips: ["scanner", "bird's-eye", "AR"],
      b: ["A homography maps one plane to another — 4 point pairs are enough.",
          "Perspective warp → document scanner and bird's-eye views.",
          "Panorama stitching aligns overlapping frames into one image.",
          "HDR merges exposures for high-dynamic-range scenes (brief)."],
      note: "The document scanner is a satisfying, quick win." },
    { t: "process", h: "Camera calibration workflow", steps: ["Capture ~15 chessboard images", "Find corners (sub-pixel)", "calibrateCamera → intrinsics", "Save distortion coeffs", "Undistort live frames"],
      cap: "Calibration matters for measurement, AR and any robotics that needs metric scale.",
      note: "Explain intrinsics vs distortion and why it matters for the drone work." },
  ],
  workshop: { h: "Calibrate + scan + stitch", code: "03_features.py",
    steps: ["Capture ~15 chessboard images from the Pi camera.",
            "Compute the camera matrix + distortion; undistort a live frame.",
            "Build a document scanner using a perspective warp.",
            "Stitch a 2-image panorama."],
    deliver: "camera_intrinsics.npz + a distorted/undistorted comparison + a scanned page + a panorama.",
    note: "Keep the intrinsics file — later weeks can reuse it." },
  takeaways: ["Contours + ORB cover a lot with zero training.", "A homography needs only 4 correspondences.", "Calibration turns pixels into measurable geometry.", "Undistortion is a prerequisite for metric vision."],
  media: [
    { label: "OpenCV — feature matching & calibration (docs + video)", url: "docs.opencv.org/4.x/d6/d00/tutorial_py_root.html" }
  ],
  resources: [
    { n: "OpenCV — camera calibration tutorial", u: "docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html" },
    { n: "OpenCV — feature matching & homography", u: "docs.opencv.org/4.x/d6/d00/tutorial_py_root.html" },
    { n: "Szeliski — feature detection & alignment", u: "szeliski.org/Book" },
  ],
},
// ===================================================================== L4
{
  num: 4, slug: "RealTime_Capture_picamera2",
  title: "Real-Time Capture & Camera Systems",
  tagline: "picamera2, FPS budgets, and the ESP32 as a network camera.",
  outcomes: [
    { tag: "CLO2", text: "Build a real-time camera app on the Pi with picamera2." },
    { tag: "CLO2", text: "Measure FPS/latency and reason about resolution trade-offs." },
    { tag: "CLO2", text: "Ingest an ESP32-CAM stream as a networked camera." },
  ],
  agenda: ["The Pi camera stack", "Sensors: Module 3 / HQ / Global Shutter", "The real-time loop", "Measuring FPS & latency", "ESP32-CAM as a network camera", "Workshop: FPS baseline"],
  slides: [
    { t: "process", h: "The Pi camera stack", steps: ["Sensor", "libcamera", "rpicam-apps", "picamera2 (Python)", "your OpenCV code"],
      cap: "picamera2 gives Python access; rpicam-apps/libcamera do the heavy lifting.",
      note: "Show rpicam-hello first, then move to Python." },
    { t: "two", h: "Choosing a sensor", lh: "Module 3 / HQ", rh: "Global Shutter",
      l: ["Module 3: autofocus, great general use.", "HQ: interchangeable lenses, best optics.", "Rolling shutter — smears fast motion."],
      r: ["Freezes fast motion (no smear).", "Ideal for drones and moving targets.", "Lower resolution, but motion-accurate."],
      note: "Match sensor to the application; drones want global shutter." },
    { t: "content", h: "The real-time loop & FPS", tag: "FPS", chips: ["capture", "process", "draw"],
      b: ["Loop: capture → process → display; measure time in each stage.",
          "FPS falls as resolution rises — the recurring edge dilemma.",
          "Threading/queues stop a slow stage from stalling capture.",
          "Today's CPU FPS table is your baseline for the Hailo NPU in L8."],
      note: "Have them literally record the numbers; used later." },
    { t: "content", h: "ESP32-CAM as a network camera", tag: "MJPEG", chips: ["Wi-Fi", ":81/stream", "OpenCV"],
      b: ["CameraWebServer exposes an MJPEG stream over Wi-Fi.",
          "Typical URL: http://<ip>:81/stream.",
          "cv2.VideoCapture(url) reads it straight into OpenCV on the Pi.",
          "Now the cheap ESP32 becomes an input to the Pi/Hailo pipeline."],
      note: "This bridges the MCU tier into the Pi pipeline." },
  ],
  workshop: { h: "Live app + FPS table + ESP32 ingest", code: "04_picamera2_stream.py · 08_esp32cam_stream_ingest.py",
    steps: ["Stream from the Pi camera with a live FPS overlay + one Canny op.",
            "Sweep resolution 640×480 → 1280×720 → 1920×1080; record FPS.",
            "Ingest the ESP32-CAM stream on the Pi.",
            "Interpret the FPS-vs-resolution trend in two sentences."],
    deliver: "FPS-vs-resolution table + interpretation + an ESP32 feed screenshot (this is the CPU baseline for L8).",
    note: "The FPS table is reused to compute NPU speed-up in L8." },
  takeaways: ["picamera2 is your real-time Python entry point.", "Global shutter matters for motion and drones.", "FPS vs resolution vs accuracy is a constant trade-off.", "The ESP32 can feed the Pi pipeline over Wi-Fi."],
  media: [
    { label: "picamera2 examples (Raspberry Pi, video-ready)", url: "github.com/raspberrypi/picamera2" }
  ],
  resources: [
    { n: "picamera2 manual & examples", u: "github.com/raspberrypi/picamera2" },
    { n: "Raspberry Pi camera software (libcamera / rpicam-apps)", u: "raspberrypi.com/documentation/computers/camera_software.html" },
    { n: "Course code: 04_picamera2_stream.py", u: "applied-cv-course/code/" },
  ],
},
// ===================================================================== L5
{
  num: 5, slug: "Deep_Learning_Foundations",
  title: "Deep Learning Foundations for Vision",
  tagline: "Perceptron to CNN — the machinery, honestly.",
  outcomes: [
    { tag: "CLO3", text: "Explain backprop, activations, losses and optimisers." },
    { tag: "CLO3", text: "Describe CNN building blocks and receptive fields." },
    { tag: "CLO3", text: "Train and evaluate a small classifier in PyTorch." },
  ],
  agenda: ["Perceptron → ANN → backprop", "Activations & vanishing gradients", "Loss vs cost", "Optimisers: SGD → Adam", "CNN building blocks", "Workshop: train a classifier"],
  slides: [
    { t: "process", h: "How a network learns", steps: ["Forward pass", "Compute loss", "Backpropagation", "Update weights (optimiser)", "Repeat / evaluate"],
      cap: "Backprop is the chain rule applied across layers to get gradients.",
      note: "Keep the math intuitive; the workshop makes it concrete." },
    { t: "content", h: "Activations & the gradient", tag: "ACTIVATIONS", chips: ["ReLU", "softmax", "vanishing"],
      b: ["Sigmoid/tanh saturate → vanishing gradients in deep nets.",
          "ReLU (and leaky/ELU) keep gradients alive and train faster.",
          "Softmax turns logits into a class distribution for classification.",
          "Choice of activation shapes trainability, not just output range."],
      note: "Tie the vanishing-gradient story to why ReLU won." },
    { t: "content", h: "Loss & optimisers", tag: "OPTIMISE", chips: ["cross-entropy", "Adam", "dropout"],
      b: ["Regression → MSE; classification → cross-entropy.",
          "Optimisers: SGD → momentum → Adagrad → RMSProp → Adam (the default).",
          "Regularisation: dropout and sensible weight init fight overfitting.",
          "Learning rate is the single most important hyperparameter."],
      note: "Adam is the practical default; explain why." },
    { t: "content", h: "CNN building blocks", tag: "CONV", chips: ["conv", "pool", "receptive field"],
      b: ["Convolution learns local features; stride/padding control output size.",
          "Pooling downsamples and grows the receptive field.",
          "Deeper layers see more context (larger receptive field).",
          "Batch-norm stabilises training; a FC head maps features to classes."],
      note: "Receptive field is the concept that ties CNNs together." },
    { t: "figure", img: "figures/fig_conv.png", h: "How a convolution sees", cap: "A kernel slides over the input; stacking layers grows the receptive field.", note: "Explain receptive fields with the figure." },
  ],
  workshop: { h: "Train your first classifier (PyTorch)", code: "ml/train_classifier_pytorch.py",
    steps: ["Photograph a 3–5 class dataset; arrange as ImageFolder.",
            "Build a Dataset/DataLoader and a small CNN.",
            "Train on Colab; watch train vs val accuracy.",
            "Report final accuracy + a confusion matrix."],
    deliver: "Colab notebook + accuracy curves + confusion matrix figure. Keep the dataset for L8.",
    note: "Run on Colab's free GPU; CPU is fine but slow." },
  takeaways: ["Backprop = chain rule for gradients.", "ReLU + Adam are the practical defaults.", "Convolutions + pooling build up receptive fields.", "Overfitting is fought with data, augmentation and dropout."],
  media: [
    { label: "UMich EECS 498 — Deep Learning for CV, Lecture 1 (video)", url: "youtube.com/watch?v=QytpbYkGxKo" }
  ],
  resources: [
    { n: "PyTorch — Learn the Basics", u: "pytorch.org/tutorials/beginner/basics/intro.html" },
    { n: "UMich EECS 498 — Deep Learning for CV", u: "web.eecs.umich.edu/~justincj/teaching/eecs498" },
    { n: "Stanford CS231n notes", u: "cs231n.github.io" },
  ],
},
// ===================================================================== L6
{
  num: 6, slug: "Classification_Transfer_Deploy",
  title: "Classification, Transfer Learning & Deployment",
  tagline: "Stand on giants' shoulders — then ship it.",
  outcomes: [
    { tag: "CLO3", text: "Compare CNN architectures and apply transfer learning." },
    { tag: "CLO3", text: "Use augmentation to improve generalisation." },
    { tag: "CLO8", text: "Deploy a model as a Gradio app on Hugging Face Spaces." },
  ],
  agenda: ["Architecture lineage", "Transfer learning vs pretrained", "Data augmentation", "Deploy: Gradio + HF Spaces", "Streamlit / Flask options", "Workshop: fine-tune + ship"],
  slides: [
    { t: "process", h: "Architecture lineage", steps: ["LeNet", "AlexNet / VGG", "Inception / ResNet", "MobileNet", "Vision Transformer"],
      cap: "Each step fixed a bottleneck: depth, vanishing gradients, efficiency, attention.",
      note: "Frame as problem→solution, not a list of names." },
    { t: "two", h: "Transfer learning vs from scratch", lh: "Transfer / fine-tune", rh: "From scratch",
      l: ["Start from ImageNet features.", "Works with small datasets.", "Fast, high accuracy — the default."],
      r: ["Needs huge data + compute.", "Rarely justified in practice.", "Only for very novel domains."],
      note: "Transfer learning is the practical default; make that explicit." },
    { t: "content", h: "Data augmentation", tag: "AUGMENT", chips: ["flip", "crop", "colour jitter"],
      b: ["Augmentation synthesises variety: flips, crops, colour/brightness jitter.",
          "It fights overfitting and improves real-world robustness.",
          "Albumentations / imgaug make pipelines fast and composable.",
          "Match augmentations to your deployment conditions (lighting, angle)."],
      note: "Augmentation is the cheapest accuracy you'll ever buy." },
    { t: "process", h: "From model to live demo", steps: ["Fine-tune backbone", "Wrap in Gradio", "Add requirements.txt", "Push to HF Space", "Share the URL"],
      cap: "Streamlit and Flask are alternatives; Gradio is the fastest path to a demo.",
      note: "Deployment is a first-class skill, not an afterthought." },
  ],
  workshop: { h: "Fine-tune + ship to Hugging Face", code: "apps/gradio_classifier.py",
    steps: ["Fine-tune a pretrained backbone on your L5 dataset.",
            "Build a Gradio interface around the model.",
            "Create a Hugging Face Space (SDK = Gradio) and push.",
            "Verify the live demo classifies uploaded images."],
    deliver: "A live Hugging Face Space URL + your model's accuracy on a held-out set.",
    note: "Free hosting; the URL is the deliverable." },
  takeaways: ["Architectures evolved to fix real bottlenecks.", "Transfer learning is the default for small data.", "Augmentation is cheap, high-value robustness.", "A model isn't done until someone can use it."],
  media: [
    { label: "Gradio — build & share ML demos (docs + video)", url: "gradio.app" }
  ],
  resources: [
    { n: "PyTorch — transfer learning tutorial", u: "pytorch.org/tutorials/beginner/transfer_learning_tutorial.html" },
    { n: "Gradio", u: "gradio.app" },
    { n: "Hugging Face Spaces", u: "huggingface.co/spaces" },
  ],
},
// ===================================================================== L7
{
  num: 7, slug: "Detection_I_YOLO_Family",
  title: "Object Detection I — Architectures & YOLO",
  tagline: "From R-CNN to YOLO26: one forward pass, many boxes.",
  outcomes: [
    { tag: "CLO3", text: "Explain the detection task, boxes and NMS." },
    { tag: "CLO3", text: "Interpret detection metrics: IoU and mAP." },
    { tag: "CLO4", text: "Run and compare pretrained YOLO models." },
  ],
  agenda: ["Detection vs classification", "Metrics: IoU & mAP", "Two-stage vs one-stage", "YOLO evolution → YOLO26", "Transformers & zero-shot (RF-DETR, YOLOE)", "Workshop: run & compare"],
  slides: [
    { t: "content", h: "Detection & its metrics", tag: "mAP", chips: ["IoU", "precision/recall", "NMS"],
      b: ["Detection = 'what' + 'where' (a labelled box per object).",
          "IoU measures box overlap; the match threshold defines a hit.",
          "mAP@0.5 and mAP@0.5:0.95 summarise precision/recall across classes.",
          "NMS removes duplicate boxes — unless the model is NMS-free (YOLO26)."],
      note: "Nail IoU and mAP; students conflate them constantly." },
    { t: "two", h: "Two-stage vs one-stage", lh: "Two-stage (R-CNN family)", rh: "One-stage (YOLO / SSD)",
      l: ["Propose regions, then classify.", "R-CNN → Fast → Faster → Mask R-CNN.", "Accurate but slower."],
      r: ["Single forward pass, grid-based.", "Real-time; edge-friendly.", "The practical choice for this course."],
      note: "One-stage detectors dominate edge deployment." },
    { t: "process", h: "YOLO evolution", steps: ["YOLOv5 (2020)", "YOLOv8 (2023)", "YOLO11 (2024)", "YOLOv12 (2025)", "YOLO26 (2026)"],
      cap: "YOLO26: native end-to-end, NMS-free, ~43% faster CPU inference — built edge-first.",
      note: "Confirm the exact weight filename in Ultralytics docs before class." },
    { t: "content", h: "Transformers & zero-shot", tag: "ZERO-SHOT", chips: ["RF-DETR", "YOLOE", "prompt"],
      b: ["RF-DETR brings transformer detection to real-time.",
          "YOLOE does zero-shot detection via text/visual prompts.",
          "Zero-shot = detect classes you never trained on.",
          "Great for rapid prototyping before you collect a dataset."],
      note: "Show one zero-shot query live if time allows." },
    { t: "figure", img: "figures/fig_iou.png", h: "IoU & mAP — how detection is scored", cap: "IoU is overlap ÷ union; mAP averages precision/recall across classes & thresholds.", note: "Nail IoU vs mAP here." },
  ],
  workshop: { h: "Run & compare pretrained YOLO", code: "05_yolo_pretrained.py",
    steps: ["Run YOLO26/YOLO11 on images and a webcam.",
            "Sweep confidence/IoU; watch false positives vs misses.",
            "Filter to one class (e.g. person).",
            "Log ms/frame to contrast with Hailo in L8; try one YOLOE zero-shot query."],
    deliver: "Annotated detections + a note on how thresholds traded false positives against misses.",
    note: "The CPU timing here motivates the NPU in L8." },
  takeaways: ["Detection = classification + localisation.", "IoU and mAP are distinct — know both.", "One-stage YOLO is the edge default.", "YOLO26 is NMS-free and edge-first; zero-shot skips data collection."],
  media: [
    { label: "Ultralytics YOLO26 — detection, segmentation, pose, real-time demo (2026)", url: "youtube.com/watch?v=F3ej8JG5IeY" }
  ],
  resources: [
    { n: "Ultralytics YOLO26 — edge-first vision AI", u: "ultralytics.com/blog/ultralytics-yolo26-the-new-standard-for-edge-first-vision-ai" },
    { n: "YOLO evolution survey (arXiv 2510.09653)", u: "arxiv.org/abs/2510.09653" },
    { n: "RF-DETR", u: "github.com/roboflow/rf-detr" },
  ],
},
// ===================================================================== L8
{
  num: 8, slug: "Detection_II_Custom_Hailo",
  title: "Object Detection II — Custom Data + Hailo NPU",
  tagline: "Train it, quantise it, compile it, run it at 30 FPS.",
  outcomes: [
    { tag: "CLO4", text: "Label, split and train a custom detector." },
    { tag: "CLO5", text: "Compile a model to a Hailo .hef and deploy on the Pi." },
    { tag: "CLO5", text: "Quantify the NPU speed-up over the CPU baseline." },
  ],
  agenda: ["Dataset lifecycle (Roboflow)", "Training a custom YOLO", "Why NPUs exist", "The .hef deploy chain", "CPU vs NPU benchmarking", "Workshop / Mid project"],
  slides: [
    { t: "process", h: "Dataset lifecycle", steps: ["Collect images", "Label (Roboflow)", "Split train/val", "Augment", "Train + evaluate"],
      cap: "Aerial datasets like VisDrone are great for drone-facing projects.",
      note: "Good data beats a bigger model almost every time." },
    { t: "content", h: "Why edge accelerators exist", tag: "NPU", chips: ["TOPS/Watt", "HailoRT", "model zoo"],
      b: ["CNNs are cheap in TOPS but expensive on a general CPU.",
          "An NPU trades flexibility for throughput-per-Watt.",
          "Hailo: HailoRT runtime + a Model Zoo of pre-compiled .hef files.",
          "A .hef is chip-specific — an 8L build won't run on 8 or 10H."],
      note: "Set up the compile chain as the core skill of the course." },
    { t: "process", h: "The deploy chain", steps: [".pt (trained)", "export ONNX", "DFC: parse", "optimise / quantise int8", "compile → .hef → Pi"],
      cap: "Keep training and compilation in separate Docker containers to avoid conflicts.",
      note: "This compile-once/deploy-many split is the key mental model." },
    { t: "stats", h: "The payoff: CPU vs NPU", stats: [{ n: "~5 FPS", l: "YOLO on Pi 5 CPU (baseline)" }, { n: "30+ FPS", l: "same model on Hailo NPU" }, { n: "int8", l: "quantised for the edge" }],
      note: "Numbers are indicative; students measure their own." },
  ],
  workshop: { h: "Mid project — custom detector on the NPU", code: "07_train_export_compile.sh · 06_hailo_picamera2_detect.py",
    steps: ["Label a small custom set (PPE / pothole / your target).",
            "Train YOLO, export ONNX, compile to .hef with the DFC.",
            "Deploy on Pi + Hailo; measure on-device FPS.",
            "Compare against the L4 CPU baseline; compute the speed-up."],
    deliver: "Working NPU detector + 2-page report: dataset, curves, quantisation notes, on-device FPS, one bug you fixed.",
    note: "This is the graded mid-term project." },
  takeaways: ["Labelling quality drives detector quality.", "NPUs win on throughput-per-Watt, not flexibility.", "The chain is .pt → ONNX → DFC → .hef.", "Quantisation trades a little accuracy for a lot of speed."],
  media: [
    { label: "Computer vision on the edge — RPi 5 + Hailo object detection (2025)", url: "youtube.com/watch?v=xiHv7xd1drY" },
    { label: "Train YOLO26 on a custom dataset in Google Colab (2026)", url: "youtube.com/watch?v=7lZa3Yi2kbo" }
  ],
  resources: [
    { n: "Hailo RPi examples (maintained)", u: "github.com/hailo-ai/hailo-apps" },
    { n: "Seeed wiki — YOLOv8n on Pi 5 AI Kit", u: "wiki.seeedstudio.com/tutorial_of_ai_kit_with_raspberrypi5_about_yolov8n_object_detection" },
    { n: "Roboflow — how to label data", u: "blog.roboflow.com/how-to-label-data" },
  ],
},
// ===================================================================== L9
{
  num: 9, slug: "Tracking_Counting_Analytics",
  title: "Multi-Object Tracking, Counting & Analytics",
  tagline: "From per-frame boxes to stable IDs and business logic.",
  outcomes: [
    { tag: "CLO4", text: "Explain the association problem and modern trackers." },
    { tag: "CLO4", text: "Build counting, speed and zone-logic on top of detection." },
    { tag: "CLO4", text: "Ship a working analytics app." },
  ],
  agenda: ["Detection → tracking", "The association problem", "SORT → DeepSORT → ByteTrack", "Counting, speed, heatmaps", "Real briefs (traffic, sport, LPR)", "Workshop: counter app"],
  slides: [
    { t: "content", h: "Why tracking?", tag: "IDs", chips: ["association", "Kalman", "stable ID"],
      b: ["Detection is per-frame; tracking gives each object a stable ID over time.",
          "The core problem: associate this frame's boxes with last frame's tracks.",
          "IoU + a Kalman motion model predict where each track should be.",
          "Stable IDs are what make counting and speed possible."],
      note: "Without IDs you can't count or measure speed." },
    { t: "process", h: "Tracker lineage", steps: ["SORT", "DeepSORT (appearance)", "ByteTrack", "BoT-SORT"],
      cap: "Ultralytics ships ByteTrack/BoT-SORT built in — model.track(persist=True).",
      note: "Use the built-in tracker in the workshop." },
    { t: "content", h: "From tracks to analytics", tag: "ANALYTICS", chips: ["count", "speed", "zones"],
      b: ["Line-crossing → entering/leaving counts.",
          "Displacement / time → speed estimation.",
          "ROIs and zones → dwell time, occupancy, alerts.",
          "Aggregate over time → heatmaps and trends."],
      note: "This logic layer turns a demo into a product." },
    { t: "content", h: "Real-world briefs", tag: "APPLIED", chips: ["traffic", "sport", "LPR"],
      b: ["Traffic: vehicle counting + speed + direction.",
          "Retail/venues: people counter (in/out), occupancy.",
          "Sport: player and ball tracking, analytics.",
          "Security: license-plate detection + OCR pipeline."],
      note: "Map these to the capstone brief bank." },
  ],
  workshop: { h: "A counting / analytics app", code: "09_tracking_counting.py",
    steps: ["Add Ultralytics tracking to a detector (persist IDs).",
            "Count objects crossing a line (in/out).",
            "Estimate rough speed from centre displacement.",
            "Render a live tally overlay."],
    deliver: "A clip with stable IDs + in/out counts + a speed readout, plus your event-logic snippet.",
    note: "Emphasise the association intuition before the code." },
  takeaways: ["Tracking = association over time.", "Stable IDs unlock counting and speed.", "ByteTrack/BoT-SORT are strong, built-in defaults.", "The logic layer is where value is created."],
  media: [
    { label: "YOLO26 for video analytics — tracking & counting (2026)", url: "youtube.com/watch?v=IYKouYLYqX8" }
  ],
  resources: [
    { n: "Ultralytics — tracking mode", u: "docs.ultralytics.com/modes/track" },
    { n: "Ultralytics — solutions (counting, speed, heatmaps)", u: "docs.ultralytics.com/solutions" },
    { n: "ByteTrack", u: "github.com/ifzhang/ByteTrack" },
  ],
},
// ===================================================================== L10
{
  num: 10, slug: "Segmentation_Pose_Interaction",
  title: "Segmentation, Pose & Human Interaction",
  tagline: "Pixels, keypoints and gestures — beyond the box.",
  outcomes: [
    { tag: "CLO4", text: "Distinguish semantic vs instance segmentation and run a model." },
    { tag: "CLO6", text: "Use SAM for promptable segmentation." },
    { tag: "CLO4", text: "Build a MediaPipe hand-gesture controller." },
  ],
  agenda: ["Semantic vs instance", "FCN → U-Net → Mask R-CNN", "Segment Anything (SAM)", "Pose estimation", "MediaPipe interaction", "Workshop: segment + gesture"],
  slides: [
    { t: "two", h: "Two kinds of segmentation", lh: "Semantic", rh: "Instance",
      l: ["Label every pixel by class.", "Doesn't separate objects.", "e.g. road vs sky vs car (all cars = one)."],
      r: ["Separate each object instance.", "Boxes + per-object masks.", "Mask R-CNN, YOLO-seg."],
      note: "The distinction guides model choice." },
    { t: "content", h: "Segmentation architectures", tag: "MASKS", chips: ["U-Net", "Mask R-CNN", "SAM 3"],
      b: ["Encoder-decoder with up/downsampling; transposed conv upsamples.",
          "U-Net is the workhorse; Mask R-CNN adds instance masks.",
          "SAM 3 (Meta, Nov 2025) is promptable by clicks, boxes and text — and tracks in video.",
          "YOLO-seg gives real-time instance masks on the edge."],
      note: "SAM is a great zero-shot demo." },
    { t: "content", h: "Pose & keypoints", tag: "POSE", chips: ["OpenPose", "YOLO-pose", "keypoints"],
      b: ["Pose estimation predicts skeleton keypoints, not boxes.",
          "OpenPose (classic) and YOLO-pose (real-time) are common.",
          "Keypoints power activity recognition and safety logic.",
          "e.g. 'hand in restricted zone' → trigger an alert."],
      note: "Connect pose to actionable logic." },
    { t: "content", h: "MediaPipe for interaction", tag: "MEDIAPIPE", chips: ["hands", "face", "CPU"],
      b: ["MediaPipe runs hands/face/pose fast on CPU — no GPU needed.",
          "Hand landmarks → gesture control (pinch, distance, count).",
          "Great for HCI: volume, brightness, or a drone parameter.",
          "Low-latency and reliable for live demos."],
      note: "The gesture dial is the workshop." },
  ],
  workshop: { h: "Segment + control by gesture", code: "10_mediapipe_gesture.py",
    steps: ["Run YOLO-seg or SAM on your images.",
            "Build a MediaPipe hand tracker.",
            "Map thumb–index distance to a 0–100 value (a dial).",
            "Drive something with it (LED / volume / parameter)."],
    deliver: "A segmentation output + a working gesture demo (video).",
    note: "Calibrate the distance range to the room's camera setup." },
  takeaways: ["Semantic ≠ instance segmentation.", "U-Net and Mask R-CNN are the staples; SAM is promptable.", "Pose gives actionable keypoints.", "MediaPipe makes rich interaction cheap and CPU-friendly."],
  media: [
    { label: "Meta SAM 3 — unified detection, segmentation & tracking (2025)", url: "youtube.com/watch?v=G4OLPDjwncw" },
    { label: "MediaPipe hand tracking with OpenCV — step by step", url: "youtube.com/watch?v=RRBXVu5UE-U" }
  ],
  resources: [
    { n: "Meta Segment Anything (SAM 3, 2025)", u: "ai.meta.com/sam3" },
    { n: "MediaPipe solutions (hands/face/pose)", u: "ai.google.dev/edge/mediapipe/solutions/guide" },
    { n: "Ultralytics — segmentation & pose tasks", u: "docs.ultralytics.com/tasks" },
  ],
},
// ===================================================================== L11
{
  num: 11, slug: "TinyML_ESP32_Arduino",
  title: "TinyML Vision on Microcontrollers",
  tagline: "Machine learning in a milliwatt: ESP32-CAM & Arduino.",
  outcomes: [
    { tag: "CLO5", text: "Explain embedded ML and the FOMO detection approach." },
    { tag: "CLO5", text: "Train and deploy an on-device model with Edge Impulse." },
    { tag: "CLO5", text: "Integrate the ESP32-CAM with sensors and the Pi pipeline." },
  ],
  agenda: ["What is TinyML?", "Edge Impulse workflow", "FOMO object detection", "ESP32/Arduino project family", "Two roles for the ESP32-CAM", "Workshop: FOMO + sensor"],
  slides: [
    { t: "content", h: "TinyML: ML in a milliwatt", tag: "TinyML", chips: ["KB RAM", "~mW", "always-on"],
      b: ["Inference on microcontrollers: KB of RAM, milliwatt power.",
          "Enables always-on, private, offline sensing at the extreme edge.",
          "Trade-off: tiny models, low resolution, simple tasks.",
          "Perfect for a cheap 'is something there?' trigger."],
      note: "Set expectations: capable but constrained." },
    { t: "process", h: "Edge Impulse workflow", steps: ["Collect", "Label", "DSP block", "Train", "Deploy as Arduino lib"],
      cap: "One-click export to an Arduino library — flash straight to the ESP32-CAM.",
      note: "FOMO is the memory-friendly detection block." },
    { t: "content", h: "FOMO — tiny object detection", tag: "FOMO", chips: ["centroids", "96×96", "fits MCU"],
      b: ["FOMO = Faster Objects, More Objects — centroid detection.",
          "Predicts object centres, not full boxes — cheap on memory.",
          "96×96 grayscale input fits comfortably on the ESP32-CAM.",
          "Ideal when you need counts/positions, not precise boxes."],
      note: "Explain why FOMO fits where YOLO won't." },
    { t: "content", h: "The ESP32/Arduino project family", tag: "PROJECTS", chips: ["counter", "pan-tilt", "door lock"],
      b: ["Vision + sensor projects: object counter, gesture-controlled light.",
          "Pan-tilt tracker, ultrasonic/water-level logger, IMU monitor.",
          "Face door-lock, data logging to a database.",
          "Two roles: standalone TinyML, or a networked camera into the Pi."],
      note: "Draw from the Arduino project bank for ideas." },
  ],
  workshop: { h: "FOMO on-device + a sensor project", code: "esp32cam/README_esp32cam.md",
    steps: ["Train a 2–3 class FOMO model in Edge Impulse.",
            "Deploy it to the ESP32-CAM and view detections.",
            "Wire one sensor behaviour (pan-tilt follow or gesture → LED).",
            "Add a row to your MCU/CPU/NPU tier comparison table."],
    deliver: "On-device FOMO detection video + your completed tier comparison row.",
    note: "The tier comparison is the intellectual payoff — insist on measured numbers." },
  takeaways: ["TinyML brings ML to milliwatt devices.", "Edge Impulse exports a ready-to-flash Arduino library.", "FOMO trades boxes for centroids to fit tiny memory.", "The ESP32-CAM is either a smart sensor or a network camera."],
  media: [
    { label: "ESP32-CAM object detection with Edge Impulse FOMO (video)", url: "youtube.com/watch?v=HDRvZ_BYd08" }
  ],
  resources: [
    { n: "Edge Impulse — ESP32 docs", u: "docs.edgeimpulse.com/hardware/boards/espressif-esp32" },
    { n: "FOMO on ESP32-CAM (Makerguides)", u: "makerguides.com/train-an-object-detection-model-with-edge-impulse-for-esp32-cam" },
    { n: "Harvard/Google TinyML courseware", u: "github.com/tinyMLx/courseware/tree/master/edX" },
  ],
},
// ===================================================================== L12
{
  num: 12, slug: "ViT_VLM_VisionLanguage",
  title: "Vision Transformers, VLMs & Vision-Language",
  tagline: "Attention, CLIP and models that read a scene.",
  outcomes: [
    { tag: "CLO6", text: "Explain ViT: patches, attention and multi-head." },
    { tag: "CLO6", text: "Use CLIP for zero-shot classification and visual search." },
    { tag: "CLO6", text: "Apply a VLM to captioning / VQA / OCR." },
  ],
  agenda: ["From CNN to Transformer", "ViT: patches & attention", "CLIP & contrastive alignment", "VLMs: caption, VQA, OCR", "Industry patterns", "Workshop: CLIP search + VQA"],
  slides: [
    { t: "content", h: "Vision Transformers (ViT)", tag: "ViT", chips: ["patches", "Q·K·V", "multi-head"],
      b: ["Split the image into patches; add position; treat as tokens.",
          "Attention = Query·Key·Value: each patch attends to relevant patches.",
          "Multi-head attention asks several questions in parallel.",
          "Residuals + normalisation keep deep transformers trainable."],
      note: "Keep attention intuitive: it's a learned, weighted lookup." },
    { t: "content", h: "CLIP: images meet text", tag: "CLIP", chips: ["contrastive", "zero-shot", "search"],
      b: ["CLIP aligns image and text embeddings in one shared space.",
          "Zero-shot: classify by comparing an image to text labels.",
          "Visual search: rank images by similarity to a text query.",
          "No task-specific training needed for many use cases."],
      note: "CLIP is the workhorse for zero-shot and search." },
    { t: "content", h: "Vision-Language Models", tag: "VLM", chips: ["caption", "VQA", "OCR"],
      b: ["VLMs take an image + a prompt and answer in language.",
          "Captioning, visual question answering (VQA), scene description.",
          "OCR and document understanding with a multimodal model.",
          "A VLM 'appears to know' more than it reliably does — verify outputs."],
      note: "Flag hallucination: VLMs are confident, not always correct." },
    { t: "content", h: "Industry patterns", tag: "APPLIED", chips: ["search", "CCTV", "retail"],
      b: ["Satellite/soil classification with ViT + transfer learning.",
          "Product background removal with SAM; e-commerce tagging with CLIP.",
          "CCTV analyst, retail VQA, real-estate description with a VLM.",
          "These are shipping products, not just research demos."],
      note: "Ground the abstractions in real deployments." },
    { t: "figure", img: "figures/fig_attention.png", h: "Attention: a learned, weighted lookup", cap: "Query·Key → softmax weights → weighted sum of Values.", note: "Keep attention intuitive with the figure." },
  ],
  workshop: { h: "CLIP search + VLM VQA", code: "11_clip_visual_search.py",
    steps: ["Build a CLIP zero-shot classifier over your own images.",
            "Add text→image visual search over a folder.",
            "Ask a VLM a question about a scene (VQA) or caption it.",
            "Note one case where the VLM was confidently wrong."],
    deliver: "A working CLIP search demo + one VQA example (and one failure case).",
    note: "Run on Colab if CPU is slow; models download on first use." },
  takeaways: ["ViT tokenises images and uses attention.", "CLIP aligns vision and language for zero-shot + search.", "VLMs answer in language but can hallucinate.", "Vision-language is already in production products."],
  media: [
    { label: "MediaPipe web demos — live in-browser vision tasks", url: "google-ai-edge.github.io/mediapipe-samples-web" },
    { label: "Hugging Face — image-text-to-text (VLM) live demos", url: "huggingface.co/models?pipeline_tag=image-text-to-text" }
  ],
  resources: [
    { n: "ViT paper — An Image is Worth 16×16 Words", u: "arxiv.org/abs/2010.11929" },
    { n: "CLIP", u: "github.com/openai/CLIP" },
    { n: "Hugging Face — image-text-to-text models", u: "huggingface.co/models?pipeline_tag=image-text-to-text" },
  ],
},
// ===================================================================== L13
{
  num: 13, slug: "Vision_Language_Action",
  title: "Vision-Language-Action: Perception → Behaviour",
  tagline: "The bridge from 'detecting things' to 'doing things'.",
  outcomes: [
    { tag: "CLO6", text: "Frame perception→action as an MDP with a latency budget." },
    { tag: "CLO7", text: "Explain VLAs, behaviour cloning and diffusion policies." },
    { tag: "CLO7", text: "Implement a minimal perception→action loop." },
  ],
  agenda: ["Observation → action (MDP)", "Open vs closed loop & latency", "VLA: action head on a VLM", "Diffusion policies & world models", "Where classical control stays", "Workshop: close the loop"],
  slides: [
    { t: "content", h: "The control loop, honestly", tag: "MDP", chips: ["open/closed", "3 clocks", "latency"],
      b: ["Observation → (hidden) state → action → transition, repeat.",
          "Open loop ignores feedback; closed loop corrects from what it sees.",
          "Three clocks: sensor, model and control all tick at different rates.",
          "Latency is a design input, not an afterthought."],
      note: "Latency budget is the load-bearing idea here." },
    { t: "content", h: "Vision-Language-Action models", tag: "VLA", chips: ["action head", "BC", "chunks"],
      b: ["A VLA attaches an action head to a vision-language backbone.",
          "Behaviour cloning learns actions from demonstration episodes.",
          "Actions come in chunks over a short horizon (staleness matters).",
          "Evaluation is hard — don't fool yourself with cherry-picked runs."],
      note: "Concept-forward; no need to train a VLA in class." },
    { t: "two", h: "Why not just regress the action?", lh: "Naive regression", rh: "Diffusion / flow policies",
      l: ["Averages multiple good actions.", "Two good paths → a crash down the middle.", "Unimodal, brittle."],
      r: ["Model the full action distribution.", "Sample coherent trajectories.", "Robust to multimodal behaviour."],
      note: "This is the intuition students remember." },
    { t: "content", h: "Classical robotics doesn't vanish", tag: "CONTROL", chips: ["Jacobian", "7 Hz / 400 Hz", "safety"],
      b: ["Kinematics + the Jacobian turn intent into joint/motor motion.",
          "A 7 Hz policy runs on top of a 400 Hz control loop.",
          "World models predict dynamics for planning — but error compounds.",
          "Runtime safety gates are non-negotiable for real hardware."],
      note: "Learned policies sit on top of classical control, not instead of it." },
  ],
  workshop: { h: "Close the loop (sim / mock)", code: "capstone_skeleton.py · 12_tello_detect.py",
    steps: ["Detect a target and compute its image-centre error.",
            "Turn error into a control signal (keep target centred → yaw).",
            "Run print-only first; discuss the latency budget.",
            "Note where a safety gate must sit."],
    deliver: "A perception→action loop that steers toward a detected target + a short latency/safety note.",
    note: "Never fly indoors without a cage and a spotter; keep it print-only unless safe." },
  takeaways: ["Perception→action is a closed loop with a latency budget.", "VLAs put an action head on a vision-language model.", "Diffusion policies beat naive regression on multimodal actions.", "Classical control and safety gates remain essential."],
  media: [
    { label: "LeRobot — open robot-learning stack & policy demos", url: "github.com/huggingface/lerobot" }
  ],
  resources: [
    { n: "LeRobot (Hugging Face robotics)", u: "github.com/huggingface/lerobot" },
    { n: "Diffusion Policy", u: "diffusion-policy.cs.columbia.edu" },
    { n: "DJITelloPy (Tello SDK)", u: "github.com/damiafuentes/DJITelloPy" },
  ],
},
// ===================================================================== L14
{
  num: 14, slug: "Capstone_Drone_Robot_Integration",
  title: "Capstone — Drone / Robot-Integrated Vision",
  tagline: "Make it see, decide, and act — end to end.",
  outcomes: [
    { tag: "CLO7", text: "Integrate perception into a drone/robot system that acts." },
    { tag: "CLO5", text: "Justify tier choices with measured performance." },
    { tag: "CLO8", text: "Ship a demo and a clear technical report." },
  ],
  agenda: ["The systems view", "Drone programming patterns", "Perception → action → safety", "Optional ROS 2 bridge", "Project briefs", "Capstone: build & demo"],
  slides: [
    { t: "process", h: "The systems view", steps: ["Capture", "Inference", "Track / logic", "Action", "Log / stream"],
      cap: "Reliability, thermals and graceful degradation separate a demo from a system.",
      note: "Push students to think about failure modes, not just the happy path." },
    { t: "content", h: "Drone programming patterns", tag: "DRONE", chips: ["Tello", "count", "navigate"],
      b: ["Tello / AI-drone: live object detection from the air.",
          "Aerial counting: houses, cars, crowds from above.",
          "Colour- or QR-based navigation; obstacle avoidance.",
          "Voice / LLM-with-drone; helipad landing challenges."],
      note: "These map directly to the educator project bank." },
    { t: "content", h: "Perception → action → safety", tag: "SAFETY", chips: ["deadband", "gates", "spotter"],
      b: ["Turn detections into commands (e.g. keep target centred → yaw).",
          "Deadbands and rate limits stop jittery, unsafe motion.",
          "Runtime safety gates catch bad states before they reach motors.",
          "Always test in a netted cage with a spotter."],
      note: "Safety first — reiterate before anyone flies." },
    { t: "content", h: "Optional: ROS 2 bridge", tag: "ROS 2", chips: ["topics", "vision_msgs", "nodes"],
      b: ["Publish detections as ROS 2 messages (vision_msgs).",
          "Decouple perception, planning and control into nodes.",
          "Reuse the same pipeline across drones, rovers and arms.",
          "A natural path to a UAV/UGV follow-on course."],
      note: "Optional extension for the ambitious teams." },
  ],
  workshop: { h: "Capstone — build & demo", code: "capstone_skeleton.py · 12_tello_detect.py",
    steps: ["Pick a brief; use ≥2 tiers and a logic/action layer.",
            "Integrate capture → inference → tracking/logic → action.",
            "Measure accuracy, FPS and power; justify your tier choices.",
            "Present a live (or recorded) demo."],
    deliver: "Demo + 4–6 page report (problem, tier justification, architecture, results, limitations) + a repo forked from the scaffold.",
    note: "Grade on integration and justification, not just accuracy." },
  takeaways: ["A system integrates capture → inference → logic → action.", "Drone patterns turn perception into behaviour.", "Safety gates and testing discipline are mandatory.", "Justify every tier choice with your own measurements."],
  media: [
    { label: "DJI Tello + YOLOv8 real-time detection (project + video)", url: "github.com/dp-betalock/DJITelloDrone-YOLOv8" }
  ],
  resources: [
    { n: "DJITelloPy (Tello SDK)", u: "github.com/damiafuentes/DJITelloPy" },
    { n: "Ultralytics — ROS quickstart", u: "docs.ultralytics.com/guides/ros-quickstart" },
    { n: "ROS 2 documentation", u: "docs.ros.org" },
  ],
},
];
